"""add_stats_to_user

Revision ID: 3068871b0a3d
Revises: d3c86765569d
Create Date: 2026-05-20 17:00:27.465266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3068871b0a3d'
down_revision: Union[str, Sequence[str], None] = 'd3c86765569d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('games_played', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('wins', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('losses', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'losses')
    op.drop_column('users', 'wins')
    op.drop_column('users', 'games_played')
    # ### end Alembic commands ###
